### ISSUE TITLE
Allow users to configure maximum size of chords

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#21]

**Comment by alice-i-cecile** [comment]
Another const generic let's go.

**Comment by TimJentzsch** [comment]
What exactly do you envision here? Should the `UserInput` class have the const generic which is then passed to the chord case instead of the 8?

Should the `chord` method stay as an iterator? What happens if the iterator has more items than are allowed?

Relevant code for future reference:

<https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/src/user_input.rs#L31-L48>

**Comment by alice-i-cecile** [comment]
>  Should the UserInput struct have the const generic which is then passed to the chord case instead of the 8?

This is the idea; but set a default value of 8 to avoid ergonomics regression.

> Should the chord method stay as an iterator? What happens if the iterator has more items than are allowed?

This is the same situation as we have now. We should probably have a fallible version that returns a result for dynamic keybinding use cases.
