### ISSUE TITLE
Add tools to better handle overlapping inputs

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#23]
E.g. have both `Ctrl+R` and `R` bound, but only trigger want to trigger `Ctrl+R` hotkey.

Perhaps trigger on release in case of conflict?

Specify dedicated modifier keys?

**Comment by alice-i-cecile** [comment]
The first important question is "should this be handled at the input map level, or the action state level"?

If it's at the input level, we probably want to be able to specify some buttons as "modifiers". If it's at the action level, we probably want to allow actions to take priority over others.

**Comment by ndarilek** [comment]
Background: I use lots of accessible apps, which tend to have dizzying numbers of keybindings, including multi-key bindings, or bindings to modifier keys only. I can no longer track the sheer number of keybindings at my disposal.

I think you'll likely have to do this on the action level, especially since some commands/actions might only be bound to traditional modifier keys. I.e. Ctrl or Alt on their own might be used to trigger certain actions.

My sense is that you'd probably get most of what you need with two things: a longest-match-wins strategy like what I did with bevy_input_actionmap, and some way of reproducably ordering a list of bindings. If I try binding ctrl-alt-p to something, for instance, I'd like to catch attempts to rebind alt-ctrl-p and flag that as a duplicate binding. Maybe there's an easier way to do that, but feeding in an arbitrary list of keycodes and getting back a consistent ordering to check against a master list of existing bindings would be helpful.

But maybe there's some crazy Dark Souls-ish game that needs to handle input differently, so maybe you could make the resolution strategy swappable, with `LongestMatchWins` as the default? In all the complex keybinding scenarios I've seen--screen reader, Twitter client with invisible UI, etc.--I don't ever recall seeing one where a) someone wants a shorter command to win out over a longer one and b) they don't press the modifier first in order to disambiguate their intent.

Hope that helps. Happy to expound more if it doesn't. :)

**Comment by alice-i-cecile** [comment]
Thanks, that's super useful! I'll get started with a prototype of this, and see what I can come up with.
