### ISSUE TITLE
Allow adding a multiplier for certain inputs' value

### ISSUE THREAD

**Issue by idanarye** [Leafwing-Studios/leafwing-input-manager#322]
## What problem does this solve?

When setting an action for both mouse motion and gamepad stick (classic example - camera turning) the gamepad sends values from 0 to 1 while the mouse sends values in pixels (I think?). This means the slightest move of the mouse makes the camera spin orders of magnitude faster than when pushing the thumbstick all the way.

Currently I work around this by using different actions - one for the mouse and one for the gamepad - and combining their result in the input handling system. But it would be nice if I didn't have to split the action based on input source...

## What solution would you like?

Allow setting a factor in the `InputMap` for specific inputs, and have the system that updates the `ActionState` multiply the values by that number.

## [Optional] What alternatives have you considered?

Since this is mainly a mouse problem, it could also work - and potentially be more efficient - to add a multiplier only for mouse input via a resource.

**Comment by alice-i-cecile** [comment]
Agreed: this needs a real solution. The exact mechanism requires some careful thought though.

**Comment by idanarye** [comment]
Giving the mouse a special treatment will probably be the easiest to implement, but allowing a multiplier per bind will enable things like walk modifiers.

**Comment by 100-TomatoJuice** [comment]
Hello, I would like to try to add this, but I want to get some opinions on the implementation as this is labeled controversial. This would also solve #310 along with this issue, I think? After looking around in the code, this is my current design for it. Please correct me if I am wrong about how something works, and I'd love to know any opinions on this proposal.

## How to add the multiplier to inputs
My design would be something like this:
```rust
input_map: InputMap::default()
    .insert(DualAxis::mouse_motion().with_sensitivity(0.1), Action::Look)
    .insert(DualAxis::left_stick().with_sensitivity(1.5), Action::Look)
```
The value passed in for `with_sensitivity()` would be a multiplier, 1.0 would be the default.

## Where to apply the multiplier
It might be possible to place it in `input_value()` in `input_streams.rs`. It would look something like this:
```rust
let value_in_axis_range = |axis: &SingleAxis, value: f32| -> f32 {
    if value >= axis.negative_low && value <= axis.positive_low && include_deadzone {
        0.0
    } else if axis.inverted {
        -value * axis.sensitivity
    } else {
        value * axis.sensitivity
    }
};
```
Every axis, as far as I know, uses `value_in_axis_range()`, so it might be as easy as just adding `* axis.sensitivity`. Also, from looking around a bit, every input seems to at some point call `input_value()`. So, calculating the sensitivity there will make sure all inputs will be modified if needed.

## Where to store the data
I was thinking we could store the sensitivity value in `SingleAxis` as `DualAxis` is just two `SingleAxis`. Then, we could add constructor methods as shown above for both `SingleAxis` and `DualAxis`.
```rust
// `SingleAxis` verision
#[must_use]
pub fn with_sensitivity(self, sensitivity: f32) -> SingleAxis {
    self.sensitivity = sensitivity;
    self
}

// `DualAxis` verision
#[must_use]
pub fn with_sensitivity(self, y_sensitivity: f32, y_sensitivity: f32) -> SingleAxis {
    self.x.sensitivity = x_sensitivity;
    self.y.sensitivity = y_sensitivity;
    self
}
```
## How to change the data
I think a way to change the sensitivity would be to query for `InputMap` and use `get()`. It does return `&PetitSet<UserInput, 16>` so that may be hard to work with as you have to index into the correct `UserInput`. I don't know if there can even be an easy way to do this. Do users have to look up to order they inserted the `UserInput` into `InputMap` to change the correct one? This is still an open question that I would love to hear about!
```rust
fn set_input_sensitivity(query: Query<&mut InputMap>) {
    let map = query.single();
    // Changing the mouse input sensitivity set in above example
    let input = map.get(Action::Look).get_at_mut(0).unwrap();
    input.sensitivity = 0.4;
}
```

**Comment by alice-i-cecile** [comment]
Thanks for tackling this :) I think that sounds like a very reasonable approach.

The question of modifying it later is pretty nasty: perhaps a global resource for the sensitivity of each input type would make more sense?

**Comment by 100-TomatoJuice** [comment]
> perhaps a global resource for the sensitivity of each input type would make more sense?

This does seem more ergonomic. But, the question is, what is stored in the resource? It still leads, I think, to the same scenario, right? Users can have many inputs for one action, so you would still need a list with maybe a `HashMap`. Something like `Vec<Hashmap<?, ?>>`, as there can be more than one `InputMap` that can be modified (more than one player). What would be the key to get the correct `UserInput`? This point is an issue with querying as well, but maybe easier because of filtering?

If you'd like, I can make a draft pr for this and we can discuss the issue of changing the sensitivity there?

**Comment by idanarye** [comment]
One possible advanced usecase would be different players setting different sensitivities for their gamepads. A global resource would not allow that.

I think if the path of global resource is chosen, it should be limited to mouse motion. That would simplify things greatly, and gamepads would not really benefit much from a global resource anyway (unless, maybe, it can store different multipliers for different gamepads)

**Comment by alice-i-cecile** [comment]
Yeah, make a draft PR and we can discuss it there :)
